openapi: 3.0.0
info:
  title: 'Week 10 RevoU'
  version: 1.0.0
  description: 'Transfer management api assignment'
servers:
  - url: https://amethyst-giraffe-sock.cyclic.cloud
    description: 'Production'
  - url: http://localhost:4000
    description: 'Development server'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
          example: andra
        password:
          type: string
          example: andra123
        role:
          type: string
          example: admin
    RegisterUser:
      type: object
      properties:
        username:
          type: string
          example: andra
        password:
          type: string
          minLength: 8
          pattern: "^(?=.*[0-9])(?=.*[a-zA-Z])[a-zA-Z0-9]+$"
          example: andra123
        role:
          type: string 
          enum:
            - admin
            - maker
            - approver
      required:
        - username
        - password
        - role
    LoginUser:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    TransferList:
      type: object
      properties:
        fromAccountId: 
          type: integer
          example: 123123
        toAccountId:
          type: integer
          example: 234234
        amount:
          type: integer
          example: 5000
        status:
          type: string
          example: pending
        createdDate:
          type: string
          example: 2023-08-23
    CreateTransfer:
      type: object
      properties:
        fromAccountId: 
          type: integer
          example: 123123
        toAccountId:
          type: integer
          example: 234234
        amount:
          type: integer
          example: 5000
        status:
          type: string
          example: pending
          enum:
            - pending
        createdDate:
          type: string
          example: 2023-08-23
    PatchTransferSuccess:
      type: object
      properties:
        id:
          type: string
          example: 64e7d874c2f107959d737dbe
        fromAccountId: 
          type: integer
          example: 123123
        toAccountId:
          type: integer
          example: 234234
        amount:
          type: integer
          example: 5000
        status:
          type: string
          example: approved
        createdDate:
          type: string
          example: 2023-08-23
        updatedDate:
          type: string
          format: date-time
          example: 2023-08-25
    PatchTransfer:
      type: object
      properties:
        status:
          type: string
          example: approved
          enum:
            - approved
            - rejected
    BadRequest:
      type: object
      properties:
        error:
          type: string
        message:
          type: string  
paths:
  /api/users:
    get:
      summary: 'Get all users'
      responses:
        '200':
          description: 'Successful to get all users'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /api/register:
    post:
      summary: 'Register new user'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUser'
      responses:
        '200':
          description: 'User Created'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      username:
                        type: string
                      role:
                        type: string
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '409':
          description: 'Conflict'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'            
  /api/login:
    post:
      summary: 'Login user'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUser'
      responses:
        '200':
          description: 'Login Success'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  token:
                    type: string
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '404':
          description: 'User Not Found'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /api/transfers:
    get:
      summary: 'Get Transfer List:'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 'Successful to get transfer List'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransferList'          
    post:
      summary: 'Create new transfer'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTransfer'
      responses:
        '200':
          description: 'New Transfer Created'
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/TransferList'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
  /api/transfers/{transfersId}:
    patch:
      summary: 'Edit transfer status to approved or rejected:'
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchTransfer'
      responses:
        '200':
          description: 'Successful to edit transfer status'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PatchTransferSuccess"
  