openapi: 3.0.0
info:
  title: 'Week 10 RevoU'
  version: 1.0.0
  description: 'Transfer management api assignment'
servers:
  - url: http://localhost:4000
    description: 'Development server'
components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'Bearer with JWT Token'
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        role:
          type: string
    RegisterUser:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
          minLength: 8
          format: ^(?=.*[a-zA-Z])(?=.*\d).+$
        role:
          type: string 
      required:
        - username
        - password
        - role
    LoginUser:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    BadRequest:
      type: object
      properties:
        error:
          type: string
paths:
  /api/users:
    get:
      summary: 'Get all users'
      responses:
        '200':
          description: 'Successful to get all users'
          content:
            application/json:
              schema:
                type: array
                items:
                $ref: '#/components/schemas/User'
  /api/register:
    post:
      summary: 'Register new user'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUser'
      responses:
        '200':
          description: 'User Created'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      username:
                        type: string
                      role:
                        type: string
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'           
  /api/login:
    post:
      summary: 'Login user'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUser'
      responses:
        '200':
          description: 'Login Success'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: string
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
